#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking for this connection
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp $SCP_OPTIONS -i "$ssh_key" "$file_path" "$username"@"$server_ip":~

echo "File transferred successfully to $server_ip"
