#!/usr/bin/env bash
# Bash script that configures an Nginx server to have custom 404 page with a custom text

sudo apt-get -y update
sudo apt-get -y install nginx

# Create a custom index page
echo "Hello World!" > /var/www/html/andrew.html

# Create a custom 404 page
# echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html
# sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Check if the backup file exists for the original `default` file.
# This is meant to back up the file once the first time, after installing nginx.
# if [ ! -f /etc/nginx/sites-available/default.bak ]; then
#     sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
# fi
# 
# if [ ! -f /etc/nginx/sites-enabled/default.bak ]; then
#     sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
# fi

# Modify the `default` file to add your server block configuration
sudo bash -c 'cat <<EOL > /etc/nginx/sites-enabled/default
server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index andrew.html index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/unawarexi;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}
EOL'

sudo service nginx restart
