#!/usr/bin/env bash
# This script appends a string to a file infinitely with a 2-second delay between each iteration.

while true; do
    sudo bash -c 'echo "I am alive!" >> /tmp/my_process'
    # echo "I am alive!" >> /tmp/my_process
    sleep 2
done

