#!/usr/bin/env bash
# This script displays "Best School" 10 times except for the 4th and 8th iteration.
while read -r line
do
    username=$(echo "$line" | cut -d ':' -f1)
    user_id=$(echo "$line" | cut -d ':' -f3)
    home_path=$(echo "$line" | cut -d ':' -f6)
    echo "$username:$user_id:$home_path"
done < /etc/passwd
