#!/usr/bin/env bash
# This script displays "Best School" 10 times except for the 4th and 8th iteration.
n=0
while [ $n -lt 10 ]
do
    n=$(( n + 1 ))

    if [ $n == 4 ]
    then
        echo "bad luck"
    elif [ $n == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
