#!/usr/bin/env bash
# This script displays numbers from 1 to 20.
hour=0

while [ $hour -le 12 ]
do
    minute=1
    echo "Hour: ${hour}"

    while [ $minute -lt 60 ]
    do
        echo $minute
        minute=$(( minute + 1 ))
    done

    hour=$(( hour + 1 ))
done
